### ISSUE TITLE
Unhandled exception during open

### ISSUE THREAD

**Issue by shytikov** [Innofactor/PluginRegistration#10]
Copied from here: https://github.com/MscrmTools/XrmToolBox/issues/484

> I was trying to open the Plugin Registration Plugin. And have got the following error message:
> "Unhandled Exception: System.ArgumentException: An item with the same key has already been added.
> at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
> at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
> at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
> at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
> at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
> at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.AddNodes(TreeNodeCollection parentNodeList, ICrmTreeNode[] nodes, Boolean checkNodes)
> at Xrm.Sdk.PluginRegistration.Controls.CrmTreeControl.LoadNodes(ICrmTreeNode[] rootNodes)
> at Xrm.Sdk.PluginRegistration.MainControl.LoadNodes(CrmViewType view)"

**Comment by imranakram** [comment]
This seems to have been resolved already.
