### ISSUE TITLE
MultiSelectOptionSet filters get deleted

### ISSUE THREAD

**Issue by Dashulol** [Innofactor/PluginRegistration#102]
The plugin doesn't support filtering plugin steps on MultiSelectOptionSet fields. If I use the official Plugin Registration Tool I can set the filters but if someone updates the step using XrmToolbox the filter will get deleted silently.

The official tool added the feature in 9.0.2.5: Added MultiSelectOptionSet types as valid for filtering plugin steps on.

**Comment by imranakram** [comment]
Thanks, please check the latest update
