### ISSUE TITLE
Doesn't implement custom action messages

### ISSUE THREAD

**Issue by cfharp** [Innofactor/PluginRegistration#11]
If you want to register a plugin against a custom action message, you have to use the Plugin Registration tool in the SDK. The XrmToolBox version doesn't yet allow custom action messages.

**Comment by shytikov** [comment]
Code of the plugin was taken from CRM SDK 5, custom messages was not present at that time...

But I will try to implement this functionality! Sounds interesting! Thanks for idea!

**Comment by cfharp** [comment]
That would explain why its missing!

I've already replaced the SDK's tool with yours as my daily driver. Luckily these scenarios come up infrequently. Thanks for your hard work!

**Comment by jazmatician** [comment]
Has this begun work? I may be able to pull it & try to add it, it should be as simple as updating the call that retrieves valid messages with the one from the latest SDK.

**Comment by jazmatician** [comment]
It wasn't working last night, but last night I forked the code and traced down where it might be filtering out those messages (and didn't find anything). Then I jump in to the tool this morning and it pulls in the new messages. Maybe I hadn't published the messages? I'll chalk it up to tiredness.

**Comment by rappen** [comment]
This actually works quite well...
See example https://jonasr.app/2020/09/pro-code-escape/#register
