### ISSUE TITLE
Implement better detection of removed, added and renamed plugins

### ISSUE THREAD

**Issue by shytikov** [Innofactor/PluginRegistration#12]
Currently `PluginRegistration` implements only basic checks is plugins exists inside assembly, but it could be very useful to implement advanced logic for troubleshooting of `Plug-in assembly does not contain the required types or assembly content cannot be updated.` error.

**Comment by rappen** [comment]
And please vote! :)
https://connect.microsoft.com/dynamicssuggestions/feedback/details/2126702/

**Comment by shytikov** [comment]
Done!

**Comment by shytikov** [comment]
Now `PluginRegistration` will provide information about plugins that are missing, and will stop processing letting user to fix error before executing request.
