### ISSUE TITLE
System.NotImplementedException thrown for SourceType = 4

### ISSUE THREAD

**Issue by Shnapster** [Innofactor/PluginRegistration#128]
The tool allows registering plugin packages and registering steps and images for the plugins contained in the package. However, it does not allow for updating the package itself when the plugin assemblies need updated. When attempting to load the update form for the package, the following error occurs.

> System.NotImplementedException: SourceType = 4

This exception is thrown in the constructor of the update form and appears to only support Database (0), Disk (1), and GAC (2) assembly sources.

```
switch (assembly.SourceType)
{
    case CrmAssemblySourceType.Database:
        radDB.Checked = true;
        break;

    case CrmAssemblySourceType.Disk:
        radDisk.Checked = true;
        break;

    case CrmAssemblySourceType.GAC:
        radGAC.Checked = true;
        break;

    default:
        throw new NotImplementedException($"SourceType = {assembly.SourceType.ToString()}");
}
```

It is great that the tool allows for registering plugin packages, but without being able to update the packages it's utilization will be limited.

**Comment by imranakram** [comment]
This is now fixed with a better message in a dialog
