### ISSUE TITLE
Confusing header - plugin to analyze?

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#13]
Updating an assembly - why Analyze?

![image](https://cloud.githubusercontent.com/assets/2572253/20306967/76e79086-ab3d-11e6-8b64-20750fcf8587.png)

**Comment by daryllabar** [comment]
I'm assuming it has to analyze the plugin assemble to determine the plugin class(es) it contain(s)...

**Comment by imranakram** [comment]
Changed text to "Select the Assembly to Load"
