### ISSUE TITLE
Version 2023.12.14 breaks XTB.

### ISSUE THREAD

**Issue by mtnmuncher** [Innofactor/PluginRegistration#138]
1. Was running 2023.12.13.
2. Prompted to update to 2023.12.14 - Failed install.
3. Reverted back to last known working version 2023.11.01

If there are missing DLLs, please provide the list so that I can avoid having to revert to an older version each time this happens.

**Comment by daryllabar** [comment]
Any error?

**Comment by mtnmuncher** [comment]
Hmm. Just tried it again. Not sure what I removed from the AppData plugin folder that fixed it. But it's working now.
