### ISSUE TITLE
Missing Plugin Class needs refresh after fixing

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#14]
If I try to update an existing assembly that misses a plugin class previously registered, I get a wonderful message informing of which classes are missing.
This makes it easy to delete the registered class (if applicable).

But when retrying to update the assembly I still get the same message of missing class.

Hitting Refresh to reload everything from CRM makes it possible to update the assembly, but this should not be necessary.

Related to #12

**Comment by imranakram** [comment]
#38 seems closely related.

**Comment by imranakram** [comment]
This is finally fixed in the latest release v3.2019.7.1
