### ISSUE TITLE
Option for profiling/debug

### ISSUE THREAD

**Issue by deepakkumar1984** [Innofactor/PluginRegistration#18]
Really awesome tool. Better than the plugin registration tool by Microsoft CRM SDK. Could you please add the profile option as well?

**Comment by ct-klein** [comment]
Any update on this possibility?

**Comment by imranakram** [comment]
It believe we have to close this without fixing unfortunately since we don't have any further support from Microsoft. Please use the official plugin registration tool for this purpose.
