### ISSUE TITLE
Bug: Not possible to lood if there exist duplicated entries

### ISSUE THREAD

**Issue by daggen** [Innofactor/PluginRegistration#19]
This is a great option to the SDK tool!
I've a problem. We imported a default solution which added all the plugins and steps one more time. Because of this there exist a lot of duplicates. This is something that the SDK tool manage but your plugin fails because key already exist. I would be great if your tool could cope with this situation as well.

Possible enhancement, a filter to show duplicate only. This would be used for us when trying to solve our problem....

**Comment by shytikov** [comment]
Thanks!

Can you explain scenario in more details? And desired behavior of the tool? I asking in like step by step story with usage scenario, so I could implement what you're looking for.

**Comment by daggen** [comment]
Sure,

Steps:
1. Open your plugin
2. It starts load assemblies, plugins and steps

Expected the list of assemblies are filled with all the assemplies, plugins etc. This list should be identical to the list produced if I use Microsoft Plugin Registration tool found in the CRM SDK

Actual it only loads the first 3 assemblies then fails. See attached file for screenshot of error message.

Background, we imported a default solution to this crm instance. Hence there are duplicates among the assemblies/plugins/steps. My guess that this is why your plugin fails

![2017-01-11 08_45_40-xrmtoolbox for microsoft dynamics crm 2011 to 2016 v1 2016 11 4](https://cloud.githubusercontent.com/assets/1481424/21839849/5348826a-d7da-11e6-9efd-cb9862ce300f.png)

**Comment by imranakram** [comment]
ping @shytikov

**Comment by imranakram** [comment]
This issue has stagnated, unable to replicate so closing it.
