### ISSUE TITLE
Adding new assembly fails

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#20]
Registering a new assembly (Dyn365) fails with error "Multiple errors occured".
Not really a good description at all, sorry... :-/
After using the PR tool from the SDK to register the new assembly, I can then use PR in XTB to update the assembly, create steps etc.

**Comment by RomanVdV** [comment]
For me too, but with message: "Unable to load the specified Plugin Assembly"
[error.txt](https://github.com/Innofactor/PluginRegistration/files/796040/error.txt)

**Comment by shytikov** [comment]
It should be fixed already with the new release.

Here is the commit: https://github.com/Innofactor/PluginRegistration/commit/7af561f0c8e4fe9b3e6b188332a2148356b487cc
