### ISSUE TITLE
List of plugins not scrollable

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#21]
There really should be a scrollbar where the green arrow is, and a splitter where the red blurb is :)

![image](https://cloud.githubusercontent.com/assets/2572253/22352823/03652794-e41e-11e6-936f-206a1aa53b17.png)

**Comment by shytikov** [comment]
You right, I will check why this happened after recompilation.

**Comment by shytikov** [comment]
Fixed. Not sure, how though... Just recompilation...
