### ISSUE TITLE
Update of exsiting step

### ISSUE THREAD

**Issue by mradell** [Innofactor/PluginRegistration#22]
Button are gone on the page. Can't change flitering attributes. 

![image](https://cloud.githubusercontent.com/assets/2803638/22466849/5ecfcdee-e7c2-11e6-99fc-f824f172086b.png)

**Comment by shytikov** [comment]
OK... This type of issues begin happening after last update, I will try to fix and will update to binary.

**Comment by shytikov** [comment]
I've uploaded fixed version. You should be able to update plugin from Store in couple minutes!
