### ISSUE TITLE
Unable to load plugin inside XrmToolBox -- Missing assembly error?

### ISSUE THREAD

**Issue by altmank** [Innofactor/PluginRegistration#26]
When I try to load the PluginRegistration plugin, I get an unhandled exception. Is this assembly something I have to manually download?

************** Exception Text **************
System.IO.FileNotFoundException: Could not load file or assembly 'McTools.Xrm.Connection, Version=1.2017.1.10, Culture=neutral, PublicKeyToken=96037217801d9658' or one of its dependencies. The system cannot find the file specified.
File name: 'McTools.Xrm.Connection, Version=1.2017.1.10, Culture=neutral, PublicKeyToken=96037217801d9658'
   at Xrm.Sdk.PluginRegistration.MainControl.<OrganizationControl_ConnectionUpdated>b__55_0(BackgroundWorker worker, DoWorkEventArgs argument)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by shytikov** [comment]
It should be part of `XTB` installation already. Can you update to most recent version of `XrmToolBox`?

**Comment by rappen** [comment]
Please reopen if issue remains.
