### ISSUE TITLE
Unable to scroll list of registrations

### ISSUE THREAD

**Issue by gregowens** [Innofactor/PluginRegistration#28]
The panel titled "Registered Plugins & Custom Workflow Activities" does not have a scroll bar. Even at high resolutions, if there are a large number of registrations, it is not possible to view the end of the list as it is obscured by the "steps" panel.

Using a mouse wheel will reveal some of the end of the list, but not all. It looks like the total scroll height is equal to the size of the application window and does not take account of the panel that displays step registration details.

The workaround is to use "find" to find the desired registration, or to do it blind by selecting a visible registration and using the down arrow until the desired registration is selected.

![image](https://user-images.githubusercontent.com/2728236/29612964-bb7ef216-87fb-11e7-9596-3c6fac436387.png)

**Comment by shytikov** [comment]
Hi,

Thanks for report! Can you tell me version of the plugin?

**Comment by gregowens** [comment]
Hi Alexey

Latest version: 3.2017.8.1

Although I note that the plug-in panel in the XrmToolBox home screen lists it as 3.1.4.0



[cid:image001.png@01D27112.146EC740]<http://www.mercuryxrm.co.uk/>

Greg Owens
Chief Technical Officer

01675 436 577 | 07929 220638
greg.owens@mercuryxrm.co.uk<mailto:greg.owens@mercuryxrm.co.uk>

[cid:image002.png@01D27112.146EC740]<http://www.mercuryxrm.co.uk/>  [cid:image003.png@01D27112.146EC740] <https://twitter.com/mercuryxrm>   [cid:image004.png@01D27112.146EC740] <https://www.linkedin.com/in/gregowensuk>
Mercury xRM – Intelligent Recruitment Software

**Comment by imranakram** [comment]
Verified that it's fixed
