### ISSUE TITLE
Plugin Registration toll

### ISSUE THREAD

**Issue by bipinshan** [Innofactor/PluginRegistration#34]
I am not able to register Service Endpoint.
 CRM online 365

**Comment by rappen** [comment]
That is correct.
The PRT for XrmToolBox is based on the latest released source code from Microsoft, and from SDK 6.0 and onwards they have not released it.
We are all sorry about that, and have encouraged MS to release current source.

**Comment by bipinshan** [comment]
Thank you for the confirmation.

**Comment by rappen** [comment]
Closing, duplicate of #36
