### ISSUE TITLE
After unregister one plugin updating dll checks for old plugin list

### ISSUE THREAD

**Issue by CRente** [Innofactor/PluginRegistration#38]
Hi.

I just hit something that I think that is a bug. I had to update a DLL to a previous version that don't have a new plugin. So to update that DLL I unregistered the plugin and tried to update the DLL. One error showed up saying:

"Following plugin are missing in the assembly: ..."

This plugin was the one I just unregistered. I needed to refresh the list to be able to update the DLL, even after the unregistering step the Plugin disapeared from the list.

Looks like something is missing to be refreshed.

**Comment by rappen** [comment]
Confirmed, I have seen this behavior too.
Ping @shytikov
