### ISSUE TITLE
Filtering Attribute field is hidden

### ISSUE THREAD

**Issue by aboodh95** [Innofactor/PluginRegistration#41]
Hi,

once you register an Update plugin you expect to set see the Filtering Attribute field but it's not showing
![image](https://user-images.githubusercontent.com/12459798/44397664-33d07180-a552-11e8-88ac-650d3f8a2734.png)

the version is 3.2018.8.2

**Comment by imranakram** [comment]
Thanks for letting us know. Will be fixing this soon.

**Comment by imranakram** [comment]
Fixed in v3.2018.8.3. Thanks once again :)
