### ISSUE TITLE
Always Sandbox for online environments

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#45]
It really does not make sense to have the option to register an assembly out of sandbox in online environments, that will always fail.
This is also what it defaults to, so changing the default to Sandbox is a good start.
Disabling None for online environments would be even better.

**Comment by imranakram** [comment]
Thanks for the input Jonas. that makes perfect sense. I'll be working on that too.

**Comment by daryllabar** [comment]
It took two years, but I didn't have to do it and it got done so I can't complain!

**Comment by imranakram** [comment]
We're still not out of the woods yet. 😐 
Apparently the `ConnectionDetail.UseOnline` property from XrmToolBox Connections project `MscrmTools.Xrm.Connection` doesn't return the correct value for online environment and the behavior is still the same in my case. This needs some attention

**Comment by imranakram** [comment]
Now ConnectionDetail.UseOnline returns the correct value.
