### ISSUE TITLE
Deleting a plugin will prevent updating the Assembly 

### ISSUE THREAD

**Issue by aboodh95** [Innofactor/PluginRegistration#48]
Hi,

in case i deleted a plug-in then i tried to update the assembly i will have message showing that the deleted plug-in is missing from the dll, i delete it

**Comment by rappen** [comment]
Try hitting Refresh, then updating the assembly.
[workaround, still agree issue should be solved]

**Comment by aboodh95** [comment]
Ya, refreshing will solve the issue, but as you say it should be fixed

**Comment by imranakram** [comment]
Thanks, I'm working on that. I've a solution which solves the issue but its quite slow so I'm trying to find a more efficient solution instead. Duplicate of #38 #14.

**Comment by imranakram** [comment]
This is finally fixed in release v3.2019.7.1.
