### ISSUE TITLE
Plugin Registration Tool Crashing with latest version of Dynamics 365 CE

### ISSUE THREAD

**Issue by bennyboy23** [Innofactor/PluginRegistration#50]
When connected to a Dynamics 365 CE environment which is on database version 9.1.0.2842 and with the april 19 preview updates enabled, the plugin registration tool in XRMtoolbox crashes.

![image](https://user-images.githubusercontent.com/6200604/54277133-ddc32a00-4586-11e9-9fff-b9137be0c411.png)

the received error is attached.

[pluginregerror.txt](https://github.com/Innofactor/PluginRegistration/files/2961295/pluginregerror.txt)

**Comment by imranakram** [comment]
Strange, I'm connected to one such environment right now

**Comment by bennyboy23** [comment]
> Strange, I'm connected to one such environment right now

Yes well for once it doesn't work on my machine 😄 does the error give you any indication of the problem? I connected via the Sdk control rather than the traditional connection method in Xrmtoolbox

**Comment by imranakram** [comment]
Good that you mentioned it. I am able to reproduce it now. We haven't updated PRT to the latest dependencies yet though so till that time, you'd have to use other methods of connections such as connection string

**Comment by imranakram** [comment]
Hi @bennyboy23, Please get the updated version. Login via SDK control works now
