### ISSUE TITLE
Unable to use the plugin reg tool with SDK login control authentication

### ISSUE THREAD

**Issue by daniele-torlai** [Innofactor/PluginRegistration#52]
It seems impossible to use the plugin logging in using a SDK login control connection.

Error message: 

> "Unable to read user password"

Stacktrace:

> System.Exception: Unable to read user password
   in McTools.Xrm.Connection.ConnectionDetail.ConnectOnline()
   in McTools.Xrm.Connection.ConnectionDetail.GetCrmServiceClient(Boolean forceNewService)
   in Xrm.Sdk.PluginRegistration.Wrappers.CrmOrganization.InitializeOrganizationService()
   in Xrm.Sdk.PluginRegistration.Wrappers.CrmOrganization.get_OrganizationService()
   in Xrm.Sdk.PluginRegistration.Helpers.OrganizationHelper.LoadMessages(CrmOrganization org, ProgressIndicator prog)
   in Xrm.Sdk.PluginRegistration.Helpers.OrganizationHelper.LoadMessages(CrmOrganization org)
   in Xrm.Sdk.PluginRegistration.Wrappers.CrmOrganization..ctor(ConnectionDetail detail, ProgressIndicator prog)
   in Xrm.Sdk.PluginRegistration.MainControl.<OrganizationControl_ConnectionUpdated>b__69_0(BackgroundWorker worker, DoWorkEventArgs argument)
   in System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   in System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

**Comment by imranakram** [comment]
Related to #50

**Comment by daniele-torlai** [comment]
The point here is i cannot switch to another connection way: my company enabled MFA so the 2 only ways to connect to CRM are the one i'm using and the direct connection string after enabling an Azure App on the tenant.
Unfortunately neither of these methods are working with XrmToolbox Plugin Reg. Tool.

**Comment by imranakram** [comment]
Hi @daniele-torlai, I see your point and working on fixing it.

**Comment by imranakram** [comment]
Thanks for your feedback. A new version has been released few minutes ago and should appear on the plugin store shortly.
