### ISSUE TITLE
SDK version recognized incorrectly

### ISSUE THREAD

**Issue by shytikov** [Innofactor/PluginRegistration#6]
Plugin registration shows incorrect (too old) version of assemblies on which plugins are based. For example, it shows that plugin is based on `SDK 5.0` while it is based on `SDK 8.0`. This probably happens due to fact that source code is based on assemblies for `CRM 2011`.

Code needs to be updated to handle more recent versions of `SDK`.

**Comment by samalex1701** [comment]
I was concerned about this too, the Update Existing Step window mentions CRM 2011 and CRM 4, so it worries me when we're developing on CRM 2013 and CRM 2015.  I love the idea of using XrmToolBox for plugin registration, I use it for dang near everything else, but is it possible to update this so it uses the latest SDK?  Thanks...

**Comment by imranakram** [comment]
It seems we're unable to get the SDK version for the assemblies already loaded in the system. So it makes sense to remove the SDK version information to avoid confusion.

**Comment by rappen** [comment]
Note that the labels mentioned by @samalex1701 are hard coded in the dialog. They should only be shown when you are connected to relevant version of CRM.

**Comment by imranakram** [comment]
Sdk version has been removed because we're unable to get the value from existing assemblies.
