### ISSUE TITLE
Tool image broken

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#67]
The tool description has an invalid icon:
![image](https://user-images.githubusercontent.com/2572253/80105465-ee5f1580-8578-11ea-93f2-30ed2a5ab0ad.png)

![image](https://user-images.githubusercontent.com/2572253/80105563-0f276b00-8579-11ea-8415-bd8ac29947c2.png)

---
- Deployment: Online
- DB Version: 9.1.0.15943
- XTB Version: 1.2020.2.37
- Tool Version: 3.2020.4.14

**Comment by rappen** [comment]
Combined with https://github.com/MscrmTools/XrmToolBox/issues/937 it makes everything die when you start PRT and don't have latest version installed.

**Comment by imranakram** [comment]
oh crap, shall I unlist from nuget? Where are those icons coming from? This one seems fine but not those you mentioned.
![image](https://user-images.githubusercontent.com/13014005/80106799-9a553080-857a-11ea-9279-2ee4a91483b8.png)

Is it from here?
![image](https://user-images.githubusercontent.com/13014005/80106893-b8bb2c00-857a-11ea-872d-89cac0c688e3.png)

**Comment by MscrmTools** [comment]
It's the one from the Nuget package

**Comment by MscrmTools** [comment]
You will need to increase the version of PRT, then create a new Nuget package with a valid icon.
I will update XrmToolBox on my side to avoid this

**Comment by rappen** [comment]
@imranakram see for example this line:
https://github.com/rappen/RelatedRecordsAnalyzer/blob/master/RelatedRecordsAnalyzer/Rappen.XTB.RRA.nuspec#L10

**Comment by imranakram** [comment]
![image](https://user-images.githubusercontent.com/13014005/80140270-fd10f100-85a7-11ea-9d23-352cfa363589.png)
This is fixed now :)
