### ISSUE TITLE
Selectign attributes for entity none explodes

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#68]
Steps registered for all entities are still possible to select attributes for.
This explodes with message that entity was not found.

See clip: https://www.screencast.com/t/2OEQgbTEHV9

---
- Deployment: Online
- DB Version: 9.1.0.15943
- XTB Version: 1.2020.2.37
- Tool Version: 3.2020.4.14

**Comment by MscrmTools** [comment]
The browse button should certainly be disabled when entity "none" is selected

**Comment by imranakram** [comment]
This should be fixed now :)
