### ISSUE TITLE
Filter by assembly properties

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#70]
It would be nice to be able to filter assemblies by type etc, see flags here:

![image](https://user-images.githubusercontent.com/2572253/80108765-f620b900-857c-11ea-9e94-08f5544727ad.png)

Simple query illustrating this:

```
<fetch>
  <entity name='pluginassembly' >
    <attribute name='name' />
    <attribute name='ishidden' />
    <attribute name='customizationlevel' />
    <attribute name='isolationmode' />
    <attribute name='ismanaged' />
    <attribute name='iscustomizable' />
    <filter>
      <condition attribute='ishidden' operator='neq' value='1' />
      <condition attribute='customizationlevel' operator='eq' value='1' />
      <condition attribute='isolationmode' operator='eq' value='2' />
      <condition attribute='ismanaged' operator='eq' value='0' />
      <condition attribute='iscustomizable' operator='eq' value='1' />
    </filter>
  </entity>
</fetch>

```

Obvious use case would be to only show unmanaged assemblies for DEV environments, where you are usually working with PRT.

---
- Deployment: Online
- DB Version: 9.1.0.15943
- XTB Version: 1.2020.2.37
- Tool Version: 3.2020.4.14

**Comment by MscrmTools** [comment]
Quite easy to add a new Properties on Settings class : HideManagedAssemblies
Then add a checkbox on the filter dialog
And finally apply that filter
I can do it in 5 minutes

**Comment by MscrmTools** [comment]
Something like that?

![image](https://user-images.githubusercontent.com/10774317/80120263-063f9500-858b-11ea-9f29-9fd22e5e42a2.png)

PR on its way

**Comment by rappen** [comment]
Then there are also IsHidden, CustomizationLevel, IsolationMode and IsCustomizable that could definitely be interesting too.

**Comment by MscrmTools** [comment]
Well, I think is managed is already enough. It tells you what you are supposed to work it or not

**Comment by rappen** [comment]
You might have a valid point... 😉

**Comment by imranakram** [comment]
And... so I close this one for now :)
