### ISSUE TITLE
Update/Register assembly screen may hide parts of the dialog

### ISSUE THREAD

**Issue by MscrmTools** [Innofactor/PluginRegistration#73]
After running PRT (I think the first time after the update), the update dialog can be too small to show all controls

![image](https://user-images.githubusercontent.com/10774317/80608080-9459c680-8a36-11ea-8b65-20c41d88998d.png)

Resizing the dialog makes the controls again

**Comment by jazmatician** [comment]
Just updated and this is still happening on 3.2020.4.15.

**Comment by Traenke5** [comment]
It's still happening on 3.2020.4.15. Leads to new classes to be left unregistered as the user can't see that he has to check them for update.

**Comment by imranakram** [comment]
Releasing an updated version very soon.

**Comment by imranakram** [comment]
This should be fixed in v`3.2020.5.1`. Feel free to reopen if you experience any issues.
