### ISSUE TITLE
Delay loading of user list

### ISSUE THREAD

**Issue by BetimBeja** [Innofactor/PluginRegistration#74]
It would be nice to load the users on-demand and not when the plugin opens, because when you have a lot of users in the environment it takes minutes to load.

The user list is necessary only to choose the Run in user's Context if I am not wrong:
![image](https://user-images.githubusercontent.com/11160171/80710075-a0a15a80-8aee-11ea-90d9-d857810fcbae.png)

Perhaps requesting only the currently configured users on load and have an option to retrieve the users if someone needs to configure the Run As feature (personally I have never used a specific user, only SYSTEM or Calling User).

---
- Deployment: Online
- DB Version: 9.1.0.16238
- XTB Version: 1.2020.4.38
- Tool Version: 3.2020.4.15

**Comment by imranakram** [comment]
Thanks for reporting this

**Comment by imranakram** [comment]
@BetimBeja How many users are we talking about approximately in this case?

**Comment by BetimBeja** [comment]
Approximately 15000 users, on-premise environment.

**Comment by imranakram** [comment]
@BetimBeja Just released v`3.2020.5.1` of the tool. Could you please test this and get back to me about the experience? I don't have an environment with this number of users :)

**Comment by BetimBeja** [comment]
Hello @imranakram ,
The tool loads without delay now, thank you.
When you open the step registration window the list of users seems to be smaller than the total, I don't know if this might cause any problem for someone.

**Comment by imranakram** [comment]
Hi @BetimBeja thanks for pointing that out, I will try and look at it more closely later on sometime. Also thinking about adding some progress notification
