### ISSUE TITLE
Run in User's Context shows incorrect value

### ISSUE THREAD

**Issue by stigdefeyter** [Innofactor/PluginRegistration#76]
When you register a plugin step and set it for example to run in the Users's context "SYSTEM (Disabled)", the next time you open the plugin step, the field "Run in Users's Context" shows "Calling User". When you check the configuration of the plugin step in the Microsoft's SDK Tool "Plugin Registration Tool", you'll see that the field "Run in Users's Context" is still registered on "SYSTEM (Disabled)"

In Plugin toolbox
![image](https://user-images.githubusercontent.com/32539382/81306061-55072780-907f-11ea-84bc-744bdb617315.png)

In Microsoft's tool
![image](https://user-images.githubusercontent.com/32539382/81305989-40c32a80-907f-11ea-941b-cfa72e653f7f.png)

**Comment by rappen** [comment]
I'm betting this is introduced by #74...

**Comment by imranakram** [comment]
Thanks, this should be fixed in the latest version
