### ISSUE TITLE
New images - default to no attributes

### ISSUE THREAD

**Issue by rappen** [Innofactor/PluginRegistration#79]
Due to performance issues discovered by Microsoft, plugin step images including All Attributes are highly discouraged.
Change the default behavior so that the user would actively have to select attributes to include, and a warning about performance issues when checking All Attributes.

**Comment by rappen** [comment]
From Marius:
* I think you should have the possibility to add all fields, but not an "add all" button. There are probably edge cases where people will have to live with checking many boxes
* Maybe add a button for "check all custom fields"?
* Add possibility to filter by field type
* Add possibility to filter by publisher/prefix

**Comment by imranakram** [comment]
Very valid points there, shout out for a PR ;)

**Comment by rappen** [comment]
I already self-assigned them... 😉
