### ISSUE TITLE
Getting error message as "ServiceEndpoint' entity doesn't contain attribute with Name = 'url'" after latest update 

### ISSUE THREAD

**Issue by vishwa2210** [Innofactor/PluginRegistration#85]
Hi Team,

I have updated plugin registration tool under XrmToolBox today with latest update. Now, after update is done, I can connect to whichever environment I want but assemblies don't get loaded and I get error message as below:

**Error Message**: 
_See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ServiceModel.FaultException`1[Microsoft.Xrm.Sdk.OrganizationServiceFault]: 'ServiceEndpoint' entity doesn't contain attribute with Name = 'url'. (Fault Detail is equal to Exception details: 
ErrorCode: 0x80041103
Message: 'ServiceEndpoint' entity doesn't contain attribute with Name = 'url'.
TimeStamp: 2020-11-16T10:49:03.0766191Z_

Please advice.

---
- Deployment: OnPremise
- DB Version: 7.0.3.152
- Connection Controls Version: 1.2020.5.33
- XrmToolBox Version: 1.2020.10.41
- Tool Version: 3.2020.11.2

**Comment by Oztrea** [comment]
indeed same issue, withou our onprem instance 8.2, it's working for the online

**Comment by bcolpaert** [comment]
same issue here

**Comment by imranakram** [comment]
Checkout the latest version released `3.2020.11.3`

**Comment by vishwa2210** [comment]
> Thanks for reporting the issue, please checkout the latest version released `3.2020.11.3`

Hi Imran,

Issue is fixed. Plugin assemblies now load as expected. Thanks for your quick action on this to fix. Appreciate it!!! 👍
