### ISSUE TITLE
Button missing to update metadata (description, friendlyname, name, activitygroupname etc)

### ISSUE THREAD

**Issue by Edwin-VC** [Innofactor/PluginRegistration#87]
Thank you for keeping this legacy tool up-to-date.

With the latest update I found that the button to save/update the assembly metadata like descriptions, names etc. is no longer available in the interface. Could this be put back in place? Or is there an alternative way to update this metadata?

Thank you!

**Comment by imranakram** [comment]
Thanks for reporting this. We'll look into fixing this soon

**Comment by radeknovak** [comment]
+1 from us.
We need it to update Activities In/Out metadata 
We had to downgrade dll to make it functional.

**Comment by imranakram** [comment]
@radeknovak @Edwin-VC Could you please share a screenshot? Is it this button you're talking about or is it something else? Cause I can see it in the latest version. 
![image](https://user-images.githubusercontent.com/13014005/101475202-62093380-394c-11eb-8db2-9d1709076947.png)

**Comment by Edwin-VC** [comment]
Thank you for the follow up.

Updating the step workd fine for me as well. It about updating the metadata. I've been using this tool forever and I think there used to be an Save/Update button but I cannot find it anymore:
![image](https://user-images.githubusercontent.com/41291991/101476630-5ae32500-394e-11eb-988a-f36dceca6e57.png)

The work-around for now is to use the original Plugin Registration Tool from the SDK/NuGet. But there is an obvious reason I still use the legacy Plugin Registration Tool.

It would be nice if this Metadata Update option is re-implemented again.

**Comment by imranakram** [comment]
Thanks for quick feedback and apologies for getting this bug introduced. Now I know what to look and will try to resolve this one

**Comment by Edwin-VC** [comment]
> Thanks for quick feedback and apologies for getting this bug introduced. Now I know what to look and will try to resolve this one

No worries. Already thankful that the Legacy Plugin Registration was recreated in this way for me to use. 😁

**Comment by imranakram** [comment]
Just published version `3.2020.12.1`, please check it out :)

**Comment by Edwin-VC** [comment]
> Just published version `3.2020.12.1`, please check it out :)

Oh yes! Works like a charm again. Thank you very much - keep up the awesome work!

**Comment by radeknovak** [comment]
Works fine. Thank you!

> > Just published version `3.2020.12.1`, please check it out :)
> 
> Oh yes! Works like a charm again. Thank you very much - keep up the awesome work!



> Just published version `3.2020.12.1`, please check it out :)

Thanks a lot! Works great!
