### ISSUE TITLE
where is the save button?

### ISSUE THREAD

**Issue by mcloof** [Innofactor/PluginRegistration#88]
Hi,
because of a bug in our organization, 
the button save was the only possibility to "publish" the plugins.

without the button, we must operate an "iisreset".

please put the button save back

---
- Deployment: OnPremise
- DB Version: 9.0.17.8
- Connection Controls Version: 1.2020.10.35
- XrmToolBox Version: 1.2020.11.42
- Tool Version: 3.2020.11.3

**Comment by imranakram** [comment]
Hi, thanks for reporting this, it should now be fixed in version `3.2020.12.1`.
