### ISSUE TITLE
Not able to see anything but MS assemblies

### ISSUE THREAD

**Issue by RhINO-CRM** [Innofactor/PluginRegistration#92]
After I downloaded the latest version only the MS assemblies are visible.
This is what it looks like when I filter away managed assemblies (this being a dev environment)

Is there some setting that I'm missing, since I'm the only one reporting this it seems as if I'm doing something wrong rather than something's not working correctly

We can drop this issue. The reason is that XrmToolBox isn't connecting to the organization I want to use for some reason, which explains the lack of assemblies

**Comment by imranakram** [comment]
Thanks, I'll close this one :)
