### ISSUE TITLE
PluginRegistration does not support MultiSelectPickList attribute type

### ISSUE THREAD

**Issue by vladimir-kovalyuk** [Innofactor/PluginRegistration#94]
Plugin Registration Tool from Microsoft supports MultiSelectPickList attributes in Plugin Steps' Filtering Attributes and Images.
This XrmToolbox plugin does not. It just does not show them within the list of attributes.
Moreover, attempt to editing the list of filtering attributes previously containing MultiSelectPickList attribute leads to losing it in the list.

**Comment by imranakram** [comment]
Which version of PRT are you using?

**Comment by vladimir-kovalyuk** [comment]
version 3.20.12.1
